### ISSUE TITLE
Improve section tag syntax

### ISSUE THREAD

**Issue by zetaraku** [ppodds/relno-action#28]
**Is your feature request related to a problem? Please describe.**

The section tag syntax `%% tagName %%` is confusing.
It looks like a single interpolation tag and it's hard to realize that the tags are used in pairs.

By reading [the example](https://github.com/ppodds/release-note/blob/master/template.md), I have no idea how the section tags work.
All I see are 4 independent section tags instead of 2 sections:

![](https://user-images.githubusercontent.com/9212875/205581072-27f395e0-6ce0-4d76-9664-af451c492f7b.png)

**Describe the solution you'd like**

Make open tag and close tag explicitly so that it's obvious where the section is.

Also, make the example more readable by inserting necessary newlines.

**Comment by ppodds** [comment]
This issue was caused by GitHub interpreting line breaks differently when previewing. GitHub treats `  \n` as a line break, but in other markdown editors, `\n` is still parsed as a line break. I will fix the example with standard markdown line break. Thank you!

**Comment by ppodds** [comment]
This problem does not seem to be as simple as we thought. If we replace the original line break with a standard line break, the result will still appear as shown in the figure below

![image](https://user-images.githubusercontent.com/11408727/205694632-0a3a768f-3fa2-46f3-b4f1-25a596539454.png)

It is weird, too. As a result, I have a different idea to solve this problem. Just change the file extension from `md` to `tmd` (template markdown file), so everyone can see the origin content directly (like the content in README)

![image](https://user-images.githubusercontent.com/11408727/205697473-6005cbef-e291-46a7-ba96-6fc1ef7b9a7f.png)

About section tag syntax, maybe you can share your idea and discuss with me.

**Comment by zetaraku** [comment]
You should put an extra line break before and after your section tag or it will be treated as a continuation of the previous line in Markdown. This may lead to some extra line breaks in the output, but it usually doesn't cause problems in Markdown.

```md
## 📝 Changelog

[compare changes]({{ compareUrl }})

%% changes %%

### {{ title }}

%% commits %%

- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ toSentence(message) }} (#{{ prNumber }})

%% commits %%

%% changes %%

<!-- Generate by Release Note -->
```

**Comment by ppodds** [comment]
> You should put an extra line break before and after your section tag or it will be treated as a continuation of the previous line in Markdown. This may lead to some extra line breaks in the output, but it usually doesn't cause problems in Markdown.
> 
> ```lisp
> ## 📝 Changelog
> 
> [compare changes]({{ compareUrl }})
> 
> %% changes %%
> 
> ### {{ title }}
> 
> %% commits %%
> 
> - {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ toSentence(message) }} (#{{ prNumber }})
> 
> %% commits %%
> 
> %% changes %%
> 
> 
> ```

In this example, it actually produces another issue.

![image](https://user-images.githubusercontent.com/11408727/205932766-e266d564-0d56-42a1-8046-4881ddaadbe9.png)

**Comment by zetaraku** [comment]
**Syntax 1** might be suitable but I haven't tested if the output would look right.
I would like to leave that to you to decide what syntax should be between `<!--` and `-->` so I'm not going to create a PR. 😄

**Comment by ppodds** [comment]
This change will be added to next major release. Thanks!

**Comment by ppodds** [comment]
@zetaraku You can view the latest change on [this branch](https://github.com/ppodds/release-note/tree/feat/template-syntax). I want to know your feedback😁

new example file

```markdown
## 📝 Changelog

[compare changes]({{ compareUrl }})

<!-- BEGIN breaking SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END breaking SECTION -->
<!-- BEGIN feat SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ generateIf(prBreaking, "⚠️ ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END feat SECTION -->
<!-- BEGIN fix SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ generateIf(prBreaking, "⚠️ ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END fix SECTION -->
<!-- BEGIN docs SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ generateIf(prBreaking, "⚠️ ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END docs SECTION -->
<!-- BEGIN chore SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ generateIf(prBreaking, "⚠️ ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END chore SECTION -->
<!-- BEGIN refactor SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ generateIf(prBreaking, "⚠️ ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END refactor SECTION -->
<!-- BEGIN test SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ generateIf(prBreaking, "⚠️ ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END test SECTION -->
<!-- Generate by Release Note -->
```

**Comment by zetaraku** [comment]
@ppodds Now the template just gets too WET :thinking:
Since the section is already customizable with JavaScript, does every type of commit requires its own template?

**Comment by ppodds** [comment]
> @ppodds Now the template just gets too WET 🤔 Since the section is already customizable with JavaScript, does every type of commit requires its own template?

Now we can set every section individually. I think this is a required feature. Maybe I can provide a solution to solve this problem:

e.g.

```markdown
...
<!-- BEGIN feat, fix, docs, chore, refactor, test SECTION -->
### {{ title }}

<!-- BEGIN commits SECTION -->
- {{ prSubtype }}{{ generateIfNotEmpty(prSubtype, ": ") }}{{ generateIf(prBreaking, "⚠️ ") }}{{ toSentence(message) }} (#{{ prNumber }})
<!-- END commits SECTION -->

<!-- END feat, fix, docs, chore, refactor, test SECTION -->
<!-- Generate by Release Note -->
```

**Comment by ppodds** [comment]
Let's track this in upstream repo.
